name: GH Pages CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Deploy to GH Pages
        run: |
          git config --global user.email "ianbrdeguzman@gmail.com"
          git config --global user.name "ianbrdeguzman"
          git remote set-url origin https://{{secrets.ACCESS_TOKEN}}>github.com/ianbrdeguzman/designo.git
          npm run deploy
